//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_Cons_CS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ConsoleSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConsoleSettings defaultInstance = ((ConsoleSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConsoleSettings())));
        
        public static ConsoleSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("connect <machine_name>")]
        public string ConnectSynopsis {
            get {
                return ((string)(this["ConnectSynopsis"]));
            }
            set {
                this["ConnectSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connects to a Speedway Reader.")]
        public string ConnectDescription {
            get {
                return ((string)(this["ConnectDescription"]));
            }
            set {
                this["ConnectDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("disconnect")]
        public string DisconnectSynopsis {
            get {
                return ((string)(this["DisconnectSynopsis"]));
            }
            set {
                this["DisconnectSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disconnects a connected Speedway Reader.")]
        public string DisconnectDescription {
            get {
                return ((string)(this["DisconnectDescription"]));
            }
            set {
                this["DisconnectDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("loadfactorysettings")]
        public string LoadFactorySettingsSynopsis {
            get {
                return ((string)(this["LoadFactorySettingsSynopsis"]));
            }
            set {
                this["LoadFactorySettingsSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Load factory settings clears the currently\r\nconnected Speedway Reader\'s current\r\n" +
            "settings, and replaces them with factory\r\ndefault settings.")]
        public string LoadFactorySetttingsDescription {
            get {
                return ((string)(this["LoadFactorySetttingsDescription"]));
            }
            set {
                this["LoadFactorySetttingsDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("loglevel <new_level>")]
        public string LogLevelSynopsis {
            get {
                return ((string)(this["LogLevelSynopsis"]));
            }
            set {
                this["LogLevelSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changes the logging level of the library to the new level.")]
        public string LogLevelDescription {
            get {
                return ((string)(this["LogLevelDescription"]));
            }
            set {
                this["LogLevelDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("queryfactorysettings [file_path]")]
        public string QueryFactorySettingsSynopsis {
            get {
                return ((string)(this["QueryFactorySettingsSynopsis"]));
            }
            set {
                this["QueryFactorySettingsSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reads the factory settings from the\r\nconnected Speedway Reader. Optionally\r\nit sa" +
            "ves them to the path specified.")]
        public string QueryFactorySettingsDescription {
            get {
                return ((string)(this["QueryFactorySettingsDescription"]));
            }
            set {
                this["QueryFactorySettingsDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("queryfeatureset [file_path]")]
        public string QueryFeatureSetSynopsis {
            get {
                return ((string)(this["QueryFeatureSetSynopsis"]));
            }
            set {
                this["QueryFeatureSetSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reads the feature set from the connected\r\nSpeedway Reader. Optionally it saves th" +
            "em\r\nto the path specified.")]
        public string QueryFeatureSetDescription {
            get {
                return ((string)(this["QueryFeatureSetDescription"]));
            }
            set {
                this["QueryFeatureSetDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("querystatus refreshtype [file_path]")]
        public string QueryStatusSynopsis {
            get {
                return ((string)(this["QueryStatusSynopsis"]));
            }
            set {
                this["QueryStatusSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reads the status from the connected\r\nSpeedway Reader. Optionally it saves\r\nthem t" +
            "o the path specified. Valid\r\nrefresh type values are: None, Everything,\r\nJustAnt" +
            "ennas, and JustGpis.")]
        public string QueryStatusDescription {
            get {
                return ((string)(this["QueryStatusDescription"]));
            }
            set {
                this["QueryStatusDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("querytags <duration_in_seconds> [file_path]")]
        public string QueryTagsSynopsis {
            get {
                return ((string)(this["QueryTagsSynopsis"]));
            }
            set {
                this["QueryTagsSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queries tags from the connected Speedway\r\nReader for the duration specified. Opti" +
            "onally\r\nit saves them to the path specified.")]
        public string QueryTagsDescription {
            get {
                return ((string)(this["QueryTagsDescription"]));
            }
            set {
                this["QueryTagsDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quit")]
        public string QuitSynopsis {
            get {
                return ((string)(this["QuitSynopsis"]));
            }
            set {
                this["QuitSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quits the console.")]
        public string QuitDescription {
            get {
                return ((string)(this["QuitDescription"]));
            }
            set {
                this["QuitDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("savesettings <file_path>")]
        public string SaveSettingsSynopsis {
            get {
                return ((string)(this["SaveSettingsSynopsis"]));
            }
            set {
                this["SaveSettingsSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saves the last known settings to the specified path.")]
        public string SaveSettingsDescription {
            get {
                return ((string)(this["SaveSettingsDescription"]));
            }
            set {
                this["SaveSettingsDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("setgpo <port_number> <new_level>")]
        public string SetGpoSynopsis {
            get {
                return ((string)(this["SetGpoSynopsis"]));
            }
            set {
                this["SetGpoSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set the specified GPO port on the connected Speedway\r\nReader to the new level.")]
        public string SetGpoDescription {
            get {
                return ((string)(this["SetGpoDescription"]));
            }
            set {
                this["SetGpoDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("updatetag <match_tag_epc> <new_tag_epc>")]
        public string UpdateTagSynopsis {
            get {
                return ((string)(this["UpdateTagSynopsis"]));
            }
            set {
                this["UpdateTagSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Singulates tags on the connected Speedway Reader. If a match\r\nis found, the match" +
            "ed tag is updated with the new tag epc.")]
        public string UpdateTagDescription {
            get {
                return ((string)(this["UpdateTagDescription"]));
            }
            set {
                this["UpdateTagDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("loadsettings <file_path>")]
        public string LoadSettingsSynopsis {
            get {
                return ((string)(this["LoadSettingsSynopsis"]));
            }
            set {
                this["LoadSettingsSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Loads the settings from the specified path and changes\r\nthe connected reader to u" +
            "se the settings.")]
        public string LoadSettingsDescription {
            get {
                return ((string)(this["LoadSettingsDescription"]));
            }
            set {
                this["LoadSettingsDescription"] = value;
            }
        }
    }
}
