//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octane_ViewModel {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class SettingsUI : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUI defaultInstance = ((SettingsUI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUI())));
        
        public static SettingsUI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("autoStartReaders.xml")]
        public string AutoStartReadersPath {
            get {
                return ((string)(this["AutoStartReadersPath"]));
            }
            set {
                this["AutoStartReadersPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoConnectReadersAsXml {
            get {
                return ((string)(this["AutoConnectReadersAsXml"]));
            }
            set {
                this["AutoConnectReadersAsXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int ConnectReaderIntervalInMs {
            get {
                return ((int)(this["ConnectReaderIntervalInMs"]));
            }
            set {
                this["ConnectReaderIntervalInMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MaxTagCollectionCount {
            get {
                return ((int)(this["MaxTagCollectionCount"]));
            }
            set {
                this["MaxTagCollectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MaxLogCollectionCount {
            get {
                return ((int)(this["MaxLogCollectionCount"]));
            }
            set {
                this["MaxLogCollectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TagCollectionPruneCount {
            get {
                return ((int)(this["TagCollectionPruneCount"]));
            }
            set {
                this["TagCollectionPruneCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int LogCollectionPruneCount {
            get {
                return ((int)(this["LogCollectionPruneCount"]));
            }
            set {
                this["LogCollectionPruneCount"] = value;
            }
        }
    }
}
